apiVersion: batch/v1
kind: Job
metadata:
  name: godialme
spec:
  template:
    spec:
      containers:
      - name: godialme
        image: quay.io/k_wall/godialme:latest
        imagePullPolicy: Always
        args: ["kwall-peng-c---ndj--obthifpb--a.bf2.kafka-stage.rhcloud.com",  "443"]
        env:
        - name: GODEBUG
          value: netdns=go+9
      restartPolicy: Never
  backoffLimit: 4
